DATA SEGMENT
ALL EQU 10;学生总人数
NAMELEN EQU 10;单个名字的长度
CLASSLEN EQU 1;班级长度
NUMBERLEN EQU 1;学号长度
SCORELEN EQU 2;分数长度

ALLSTU DB '?';加入程序中的学生总人数
; CURRENT DB ?;当前的位置

STUNAME DB ALL*NAMELEN DUP('?');姓名
STUCLASS DB ALL DUP('?');班级
STUNUMBER DB ALL DUP('?');学号
STUSCORE DB ALL*SCORELEN DUP('?');成绩

HINT DB 'Please input your selection(the number in brackets):','$'
ONE DB '(1)Entered student scores (decimal)','$'
TWO DB '(2)Display the scores sorted','$'
THREE DB '(3)Display the average score','$'
FOUR DB '(4)Display the number of each scores segment','$'
QUIT DB '(5)Exit','$'
ERR DB 'ERROR,Please input again','$'
CR = 0DH;回车符
LF = 0AH;换行符
TABLE DW CASE1,CASE2,CASE3,CASE4,CASE5,ERROR;跳转表

ADDNAME DB 'student name:',0DH,0AH,'$';添加姓名
ADDCLASS DB 'student class:',0DH,0AH,'$';添加班级
ADDNUMBER DB 'student number:',0DH,0AH,'$';添加学号
ADDSCORE DB 'student score:',0DH,0AH,'$';添加分数

FAILED DB '?';不及格
F6T7 DB '?';60~70
F7T8 DB '?';70~80
F8T9 DB '?';80~90
F9T1 DB '?';90~100
LESS60 DB 'The number less than 60 is:','$'
LESS70 DB 'The number less than 70 is:','$'
LESS80 DB 'The number less than 80 is:','$'
LESS90 DB 'The number less than 90 is:','$'
LESS100 DB 'The number less than 100 is:','$'

AVEPRINT DB 'The average number is:','$'
AVENUM DB 3 DUP('?');平均数的整数部分

SORTKIND DB 'SORT BY (1)NUMBER,(2)SCORE',0DH,0AH,'$'
SORTARRAY DB 0,1,2,3,4,5,6,7,8,9
PRINTNA DB 'Name:','$'
PRINTCL DB 'Class:','$'
PRINTNU DB 'Number:','$'
PRINTSC DB 'Score:','$'
TEMP DB 3 DUP('?')
TEMPAX DW '?'

DATA ENDS

STACK SEGMENT STACK
	DW 200 DUP(?)
STACK ENDS

CODE SEGMENT
	ASSUME CS:CODE,DS:DATA,SS:STACK
START:MOV AX,DATA
	  MOV DS,AX
	  MOV BYTE PTR[ALLSTU],0;初始化总人数

MAINLOOP:CALL SELECT
    MOV AH,1
    INT 21H;获得输入
    SUB AL,'1'
    CMP AL,0
    JL ERROR;出错
    CMP AL,5
    JG ERROR;出错
    MOV AH,0
    MOV BX,AX    
    SHL BX,1
    JMP TABLE[BX]
CASE1:MOV AH,1
    INT 21H
    CALL CRLF
    CALL ADDSTU
    CALL CRLF
    JMP MAINLOOP
CASE2:MOV AH,1
    INT 21H
    CALL CRLF
    CALL SORT
    CALL CRLF
    JMP MAINLOOP
CASE3:MOV AH,1
    INT 21H
    CALL CRLF
    CALL AVERAGE
    CALL CRLF
    JMP MAINLOOP
CASE4:MOV AH,1
    INT 21H
    CALL CRLF
    CALL CLASSIFY
    CALL CRLF
    JMP MAINLOOP
CASE5:MOV AH,1
    INT 21H
    CALL CRLF
    CALL EXIT
    CALL CRLF
    JMP MAINLOOP
ERROR:MOV AH,1
    INT 21H
    CALL CRLF
    MOV DX,OFFSET ERR
	MOV AH,9
	INT 21H
	CALL CRLF
    JMP MAINLOOP
	  
SELECT PROC NEAR;输出提示
	PUSH AX
	PUSH DX
	MOV DX,OFFSET HINT
	MOV AH,9
	INT 21H
	CALL CRLF
	MOV DX,OFFSET ONE
	MOV AH,9
	INT 21H
	CALL CRLF
	MOV DX,OFFSET TWO
	MOV AH,9
	INT 21H
	CALL CRLF
	MOV DX,OFFSET THREE
	MOV AH,9
	INT 21H
	CALL CRLF
	MOV DX,OFFSET FOUR
	MOV AH,9
	INT 21H
	CALL CRLF
	MOV DX,OFFSET QUIT
	MOV AH,9
	INT 21H
	CALL CRLF
	POP DX
	POP AX
	RET
SELECT ENDP

ADDSTU PROC NEAR;添加学生信息
	PUSH AX
	PUSH BX
	PUSH CX
	PUSH DX
	MOV BX,OFFSET STUNAME
	MOV AX,NAMELEN
	MUL ALLSTU
	ADD BX,AX
	MOV DX,OFFSET ADDNAME;添加姓名
	MOV AH,9
	INT 21H
INPUTN:MOV AH,1
    INT 21H
    CMP AL,CR
    JZ C
    MOV [BX],AL
    INC BX
    JMP INPUTN
    
  C:MOV [BX],'$'
    CALL CRLF
    MOV BX,OFFSET STUCLASS
	MOV AX,CLASSLEN
	MUL ALLSTU
	ADD BX,AX
    MOV DX,OFFSET ADDCLASS;添加班级
	MOV AH,9
	INT 21H
	MOV CL,10
	MOV DL,0
INPUTC:MOV AH,1
    INT 21H
    CMP AL,CR
    JZ N
    SUB AL,'0'
    MOV AH,0
    PUSH AX
    MOV AL,DL
    MUL CL
    POP DX
    ADD DL,AL
    JMP INPUTC
    
  N:MOV BYTE PTR[BX],DL
    CALL CRLF
    MOV BX,OFFSET STUNUMBER
	MOV AX,NUMBERLEN
	MUL ALLSTU
	ADD BX,AX
    MOV DX,OFFSET ADDNUMBER;添加学号
	MOV AH,9
	INT 21H
	MOV CL,10
	MOV DL,0
INPUTU:MOV AH,1
    INT 21H
    CMP AL,CR
    JZ S
    SUB AL,'0'
    MOV AH,0
    PUSH AX
    MOV AL,DL
    MUL CL
    POP DX
    ADD DL,AL
    JMP INPUTU
    
  S:MOV BYTE PTR[BX],DL
    CALL CRLF
    MOV BX,OFFSET STUSCORE
	MOV AX,SCORELEN
	MUL ALLSTU
	ADD BX,AX
    MOV DX,OFFSET ADDSCORE;添加分数
	MOV AH,9
	INT 21H
	MOV CL,10
	MOV DL,0
INPUTS:MOV AH,1
    INT 21H
    CMP AL,'.'
    JZ DOT
    SUB AL,'0'
    MOV AH,0
    PUSH AX
    MOV AL,DL
    MUL CL
    POP DX
    ADD DL,AL
    JMP INPUTS
DOT:MOV BYTE PTR[BX],DL
    MOV AH,1
    INT 21H
    SUB AL,'0'
    INC BX
    MOV BYTE PTR[BX],AL
    MOV AH,1
    INT 21H;读回车符
    
    MOV AL,ALLSTU;增加ALLSTU的计数
    INC AL
    MOV BYTE PTR[ALLSTU],AL
    CALL CRLF
    POP DX
    POP CX
    POP BX
	POP AX
	RET
ADDSTU ENDP

SORT PROC NEAR;排序输出
	PUSH AX
	PUSH BX
	PUSH CX
	PUSH DX
	
	MOV DX,OFFSET SORTKIND
	MOV AH,9
	INT 21H
	MOV AH,1
    INT 21H
    CMP AL,'1'
    JNZ SORTSC
	
	MOV AH,1
	INT 21H
	CALL CRLF
    MOV CL,ALLSTU
	MOV CH,0
	DEC CX
	CMP CX,0
	JZ L
LOOP1:MOV SI,CX
    MOV BX,0
    MOV DX,0
LOOP2:MOV DL,SORTARRAY[BX]
    MOV DI,DX
    MOV AL,STUNUMBER[DI]
    MOV DL,SORTARRAY[BX+1]
    MOV DI,DX
	CMP AL,STUNUMBER[DI]
	JGE CONTI
	XCHG DL,SORTARRAY[BX]
    MOV SORTARRAY[BX+1],DL
CONTI:ADD BX,1
    LOOP LOOP2
    MOV CX,SI
    LOOP LOOP1
    JMP L
    
SORTSC:MOV AH,1
	INT 21H
	CALL CRLF
    MOV CL,ALLSTU
	MOV CH,0
	DEC CX
	CMP CX,0
	JZ L
LOOP3:MOV SI,CX
    MOV AX,0
    MOV BX,0
    MOV DX,0
LOOP4:MOV AL,SORTARRAY[BX]
    MOV DH,SCORELEN
    MUL DH
    MOV DI,AX
    MOV DL,STUSCORE[DI]
    MOV AL,SORTARRAY[BX+1]
    MOV [TEMPAX],AX
    MUL DH
    MOV DI,AX
	CMP DL,STUSCORE[DI]
	JG CONTI2
	CMP DL,STUSCORE[DI]
	JNZ LESS
	MOV AL,SORTARRAY[BX];比较小数部分
    MOV DH,SCORELEN
    MUL DH
    MOV DI,AX
    MOV DL,STUSCORE[DI+1]
    MOV AL,SORTARRAY[BX+1]
    MUL DH
    MOV DI,AX
	CMP DL,STUSCORE[DI+1]
	JGE CONTI2
LESS:MOV AX,[TEMPAX]
    XCHG AL,SORTARRAY[BX]
    MOV SORTARRAY[BX+1],AL
CONTI2:ADD BX,1
    LOOP LOOP4
    MOV CX,SI
    LOOP LOOP3
    
  L:MOV CL,ALLSTU
    MOV CH,0
    MOV SI,CX
    MOV CX,0
PRINTL:MOV BX,CX;输出名字
    MOV AL,SORTARRAY[BX]
    MOV AH,0
    MOV BX,NAMELEN
    MUL BX
    MOV BX,AX
    ADD BX,OFFSET STUNAME
    MOV DX,OFFSET PRINTNA
    MOV AH,9
    INT 21H
    MOV DX,BX
    MOV AH,9
    INT 21H
    MOV DL,';'
    MOV AH,2
    INT 21H
    MOV DX,OFFSET PRINTCL;输出班级
    MOV AH,9
    INT 21H
    MOV BX,CX
    MOV AL,SORTARRAY[BX]
    MOV AH,0
    MOV BX,AX
    MOV AL,STUCLASS[BX]
    MOV AH,0
    CALL PRINTNUMBER
    MOV DL,';'
    MOV AH,2
    INT 21H
    MOV DX,OFFSET PRINTNU;输出学号
    MOV AH,9
    INT 21H
    MOV BX,CX
    MOV AL,SORTARRAY[BX]
    MOV AH,0
    MOV BX,AX
    MOV AL,STUNUMBER[BX]
    MOV AH,0
    CALL PRINTNUMBER
	MOV DL,';'
    MOV AH,2
    INT 21H
    MOV DX,OFFSET PRINTSC;输出成绩
    MOV AH,9
    INT 21H
    MOV BX,CX
    MOV AL,SORTARRAY[BX]
    MOV AH,0
    MOV BX,SCORELEN
    MUL BX
    MOV BX,AX
    MOV AL,STUSCORE[BX]
    MOV AH,0
    CALL PRINTNUMBER
    MOV DL,'.'
    MOV AH,2
    INT 21H
    MOV AL,STUSCORE[BX+1]
    MOV AH,0
    CALL PRINTNUMBER
	MOV DL,';'
    MOV AH,2
    INT 21H
	CALL CRLF
    INC CX
    CMP CX,SI
    JNZ PRINTL

    MOV BX,0
    MOV CH,0
    MOV CL,ALLSTU	
RESET:MOV SORTARRAY[BX],BL
    INC BX
    CMP BX,CX
    JNZ RESET
	
	CALL CRLF
	POP DX
	POP CX
	POP BX
	POP AX
	RET
SORT ENDP

PRINTNUMBER PROC NEAR
    PUSH BX
	PUSH CX
	PUSH DX
	
	MOV BX,OFFSET TEMP+2
    MOV CL,10
NEXTA:DIV CL
    MOV BYTE PTR[BX],AH
    DEC BX
    MOV AH,0
    CMP AL,0
    JNZ NEXTA
    
    INC BX
    MOV CX,OFFSET TEMP+3
PRINT:MOV DL,[BX]
    ADD DL,'0'
    MOV AH,2
    INT 21H
    INC BX
    CMP BX,CX
    JNZ PRINT
	
	POP DX
	POP CX
	POP BX
	RET
PRINTNUMBER ENDP

AVERAGE PROC NEAR;平均成绩
	PUSH AX
	PUSH BX
	PUSH CX
	PUSH DX
	
	MOV DX,OFFSET AVEPRINT
	MOV AH,9
	INT 21H
	
	MOV CL,ALLSTU
	MOV CH,0;CX=学生总人数
    MOV DI,0;整数部分
    MOV AL,0;小数部分
    MOV BX,0
LOOPA:ADD AL,STUSCORE[BX+1]
    CMP AL,10
    JL L10
    SUB AL,10
L10:CMC
    MOV DL,STUSCORE[BX]
    MOV DH,0
    ADC DI,DX
    ADD BX,SCORELEN
    LOOP LOOPA
    
    MOV AH,0
    PUSH AX
    MOV AX,DI
    MOV CL,ALLSTU
    DIV CL
    MOV DL,AL
    MOV DH,0
    MOV DI,DX
    MOV DL,AH
    MOV AX,DX
    MOV CH,10
    MUL CH
    MOV DX,AX
    POP AX
    ADD AX,DX
    DIV CL
    MOV AH,0
    PUSH AX
        
    MOV BX,OFFSET AVENUM+2
    MOV AX,DI
    MOV CL,10
NEXTPR:DIV CL
    MOV BYTE PTR[BX],AH
    DEC BX
    MOV AH,0
    CMP AL,0
    JNZ NEXTPR
    
    INC BX
    MOV CX,OFFSET AVENUM+3
PRIN:MOV DL,[BX]
    ADD DL,'0'
    MOV AH,2
    INT 21H
    INC BX
    CMP BX,CX
    JNZ PRIN
    
    MOV DL,'.'
    MOV AH,2
    INT 21H
    POP AX
    MOV DL,AL
    ADD DL,'0'
    MOV AH,2
    INT 21H
    CALL CRLF
    CALL CRLF
	
	POP DX
	POP CX
	POP BX
	POP AX
	RET
AVERAGE ENDP

CLASSIFY PROC NEAR;各分数段人数
	PUSH AX
	PUSH BX
	PUSH CX
	PUSH DX
	
	MOV BYTE PTR[FAILED],'0';初始化
	MOV BYTE PTR[F6T7],'0'
	MOV BYTE PTR[F7T8],'0'
	MOV BYTE PTR[F8T9],'0'
	MOV BYTE PTR[F9T1],'0'
	MOV CL,ALLSTU
	MOV CH,0;CX=学生总人数
    MOV BX,0
LOOPC:MOV AL,STUSCORE[BX]
    CMP AL,60
    JL L60
    CMP AL,70
    JL L70
    CMP AL,80
    JL L80
    CMP AL,90
    JL L90
    CMP AL,100
    JLE L100
L60:ADD BYTE PTR[FAILED],1
    JMP NEXT
L70:ADD BYTE PTR[F6T7],1
    JMP NEXT
L80:ADD BYTE PTR[F7T8],1
    JMP NEXT
L90:ADD BYTE PTR[F8T9],1
    JMP NEXT
L100:ADD BYTE PTR[F9T1],1
    JMP NEXT
NEXT:ADD BX,SCORELEN
    LOOP LOOPC
    
    MOV DX,OFFSET LESS60
    MOV AH,9
    INT 21H
    MOV DL,BYTE PTR[FAILED]
    MOV AH,2
    INT 21H
    CALL CRLF
    MOV DX,OFFSET LESS70
    MOV AH,9
    INT 21H
    MOV DL,BYTE PTR[F6T7]
    MOV AH,2
    INT 21H
    CALL CRLF
    MOV DX,OFFSET LESS80
    MOV AH,9
    INT 21H
    MOV DL,BYTE PTR[F7T8]
    MOV AH,2
    INT 21H
    CALL CRLF
    MOV DX,OFFSET LESS90
    MOV AH,9
    INT 21H
    MOV DL,BYTE PTR[F8T9]
    MOV AH,2
    INT 21H
    CALL CRLF
    MOV DX,OFFSET LESS100
    MOV AH,9
    INT 21H
    MOV DL,BYTE PTR[F9T1]
    MOV AH,2
    INT 21H
    CALL CRLF
    CALL CRLF                    
	
	POP DX
	POP CX
	POP BX
	POP AX
	RET
CLASSIFY ENDP

CRLF PROC NEAR;换行回车
	PUSH AX
	PUSH DX
	MOV DL,CR
	MOV AH,2
	INT 21H
	MOV DL,LF
	MOV AH,2
	INT 21H
	POP DX
	POP AX
	RET
CRLF ENDP

EXIT PROC NEAR;退出
    MOV AX,4C00H
	INT 21H
EXIT ENDP

CODE ENDS
	END START
